### ISSUE TITLE
embed-code-file

### ISSUE THREAD

**Issue by berot3** [zjhcn/obsidian-code-preview#1]
hi! Thanks for this plugin! 

I see some similarities with https://github.com/almariah/embed-code-file

Could you say what are the main differences (besides syntax)?

**Comment by hankjs** [comment]
The functionality of both plugins is the same.

My plugin is more about giving extra power to another plugin ([obsidian-code-run](https://github.com/zjhcn/obsidian-code-run)).

But I haven't had time to connect the two.
