### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by L-Super** [zjhcn/obsidian-code-preview#3]
当我按照如下语法加载一个`tcp.c`文件时，最后几行显示异常。我不确定是bug还是有行数限制

```preview
path: ./code/tcp.c
```
![image](https://user-images.githubusercontent.com/40905056/205496291-5db27d95-f3c3-418b-ac55-4029b750bd18.png)

最后，非常感谢作者提供了此插件，这个插件正是我所需要的，可以直接在ob里链接代码文件并预览

**Comment by hankjs** [comment]
感谢你提供的用例，已经在1.3.5版本修复。

**Comment by L-Super** [comment]
哇，这么高效的吗，感谢大佬！明天测试一下
